### ISSUE TITLE
Support importOnDuplicate for delegateAdministrator

### ISSUE THREAD

**Issue by kabo** [pepperize/cdk-organizations#1284]
Currently if I do this on an account that is already the delegated administrator, it fails.

```js
account.delegateAdministrator('something.amazonaws.com')
```

It'd be great if there was an `importOnDuplicate` option like with org/account creation to make this work.

**Comment by gshpychka** [comment]
https://github.com/pepperize/cdk-organizations/pull/963 should have fixed this, what version are you using?

**Comment by pflorek** [comment]
See https://github.com/pepperize/cdk-organizations/pull/963
