### ISSUE TITLE
nodejs16.x lambda runtime is end-of-life but still used

### ISSUE THREAD

**Issue by hertzsprung** [pepperize/cdk-organizations#1459]
cdk-organizations uses nodejs16.x lambdas [In several places](https://github.com/search?q=repo%3Apepperize%2Fcdk-organizations%20nodejs16.x&type=code) but, as reported in an automated AWS support email:

> We [AWS] are ending support for Node.js 16 in Lambda on June 12, 2024. This follows Node.js 16 End-Of-Life (EOL) reached on September 11, 2023.

**Comment by san99tiago** [comment]
+1

**Comment by san99tiago** [comment]
+1

**Comment by pflorek** [comment]
Fixed with https://github.com/pepperize/cdk-organizations/pull/1637
