### ISSUE TITLE
hard dependency on us-east-1

### ISSUE THREAD

**Issue by hans-d** [pepperize/cdk-organizations#463]
Hi,

why the hard dependency on `us-east-1` ? Afaik, the api is available now in all the regions. (https://docs.aws.amazon.com/general/latest/gr/ao.html)

**Comment by pflorek** [comment]
Hi @hans-d ,

that's great. Did you found a release note?

**Comment by hans-d** [comment]
ok, need some better reading glasses. The endpoint is still us-east-1, however it acts as a global service, so all regions should be useable re the accounts/organizations.

**Comment by pflorek** [comment]
@hans-d just updated the readme. is it better to read now?
