### ISSUE TITLE
Question about account creation

### ISSUE THREAD

**Issue by coltenkrauter** [pepperize/cdk-organizations#560]
When creating a new AWS account using CDK, is that the same as creating a new AWS account via the [AWS UI](https://portal.aws.amazon.com/billing/signup?nc2=h_ct&src=header_signup&redirect_url=https%3A%2F%2Faws.amazon.com%2Fregistration-confirmation#/start/email)?

How will I know what password to log in to the new account?

It seems to me, that in a case where I want to manage 10 AWS accounts, I will only need to create 1 account manually, the main account that will create the organization. From there, all other accounts can be created from CDK. Is that correct?

**Comment by pflorek** [comment]
Yes, creating an account by this construct is the same as using the UI. This construct is using the SDK and API under the hood.

For each account one has to provide an unique email in the AWS organization. AWS organization sends an email to that address. But in general you won't need or don't want that member account email. AWS organization won't send you the initial created password, you may have to reset it.

As the root user in the AWS organization you can create your own IAM user in your management account. From within your management account you can get access to each member account by using the default role `OrganizationAccountAccessRole`.

The account email for the member accounts should be verified, but must not. Just to ensure it's correct. See this [example ](https://github.com/pepperize/cdk-organizations-example/blob/main/src/example-stack.ts#L50)

**Comment by coltenkrauter** [comment]
Thanks for the quick response @pflorek, that is fantastic. Just what I wanted to hear. This is a nifty package. I look forward to using it soon.

I intend to use [plus addressing](https://www.fastmail.help/hc/en-us/articles/360060591053-Plus-addressing-and-subdomain-addressing) so I can reuse the same email account as follows:

```python
# Plus addressing
myemail+project1@example.com
myemail+project2@example.com
myemail+project3@example.com
```
