### ISSUE TITLE
Add support for new accounts to use the same payment method

### ISSUE THREAD

**Issue by coltenkrauter** [pepperize/cdk-organizations#564]
Is it possible to have new accounts automatically use the same payment method as the management account?

**Comment by pflorek** [comment]
Isn't it that the default behavior? The management account pays the bills. https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/useconsolidatedbilling-procedure.html

**Comment by coltenkrauter** [comment]
Okay, that makes sense. Thx
