### ISSUE TITLE
Suggestion to add info to releases

### ISSUE THREAD

**Issue by coltenkrauter** [pepperize/cdk-organizations#651]
I often look through release notes to understand what fixes/enhancements are being shipped. It is useful so that I am aware of what risks may be associated with a new release.

Would you be willing to add such notes to GitHub releases going forward?

**Comment by pflorek** [comment]
@coltenkrauter 

I assume it's only the convential type `chore` that is missing on the release pages. Is there a projen configuration already to print chore Messages also?

Additional there is an option to generate a markdown file of all the changes. For example with https://github.com/conventional-changelog/conventional-changelog 

The last fix [0.6.16](https://github.com/pepperize/cdk-organizations/releases/tag/v0.6.16) was the one that broke some constructs in my organizations. It really should have been breaking die to changes of the construct tree

**Comment by coltenkrauter** [comment]
Oh, that makes sense. I went back a bit and I see that you do enter release notes. Thanks for doing that 😆 

That said, it is a bummer that the `chore` releases are blank. I don't know much about this `chore` stuff. How is `chore` used and what package implements it?

**Comment by pflorek** [comment]
@coltenkrauter found it here https://github.com/projen/projen/blob/20cce2e2beb7f9882a57f044f5a4cab5b686ebbd/src/release/release.ts#L164-L170

**Comment by pflorek** [comment]
It will then look like https://github.com/pepperize/cdk-apigateway-swagger-ui/releases/tag/v0.0.31

**Comment by coltenkrauter** [comment]
Great, thanks for this.
