### ISSUE TITLE
Deleting Account resource fails

### ISSUE THREAD

**Issue by kfor90** [pepperize/cdk-organizations#761]
Hi there,

I'm getting the following Cloud Formation error when deleting an `Account` resource from my stack code:

```shell
Received response status [FAILED] from custom resource. Message returned: client.closeAccount is not a function
```

My stack code deployed no problem. The error arises when I remove the `Account` resource code and redeploy.

Sample code is as follows:

```typescript
import { Account, Organization, OrganizationalUnit } from "@pepperize/cdk-organizations";
import { Stack } from "aws-cdk-lib";

export class OrganizationStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    // Create your organization
    const organization = new Organization(stack, "Organization", {});

    // Create an organizational unit (OU)
    const organizationUnit = new OrganizationalUnit(stack, "OrganizationalUnit", {
      organizationalUnitName: "MyFirstOU",
      parent: organization.root,
    });

    // Create an account
    const account = new Account(stack, "Account", {
      accountName: "MyFirstAccount",
      email: "<your email for the member account>",
      parent: organizationUnit,
    });
  }
}
```

**Comment by npvisual** [comment]
Had the same issue, testing the creation and removal of an account within an organization with the `removal_policy=RemovalPolicy.DESTROY` property, using the code snippet below (email was modified for this comment) :

```
        # Create an account
        account2 = Account(self, "Account2",
            account_name="dev2",
            email=f"account2@xyz.com",
            parent=organization2.root,
            removal_policy=RemovalPolicy.DESTROY,
            iam_user_access_to_billing=IamUserAccessToBilling.DENY
        )
```

org-stack: creating CloudFormation changeset...
1:02:12 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource              | Account2CreateAccount42D5B361
Received response status [FAILED] from custom resource. Message returned: client.closeAccount is not a function

Logs: /aws/lambda/org-stack-cdkorganization-IsCompleteHandlerFunctio-6W1npaBp6kAm

at close (/var/task/index.js:134:16)
at Runtime.handler (/var/task/index.js:74:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5) (RequestId: 13c4caa5-bb1c-4b59-b489-ffcc83d7597e)

1:05:38 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource              | Account2CreateAccount42D5B361
Received response status [FAILED] from custom resource. Message returned: client.closeAccount is not a function

Logs: /aws/lambda/org-stack-cdkorganization-IsCompleteHandlerFunctio-6W1npaBp6kAm

at close (/var/task/index.js:134:16)
at Runtime.handler (/var/task/index.js:74:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5) (RequestId: 7db042ea-7a9e-434a-98c9-d3b676625f40)

1:08:44 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource              | Account2CreateAccount42D5B361
Received response status [FAILED] from custom resource. Message returned: client.closeAccount is not a function

Logs: /aws/lambda/org-stack-cdkorganization-IsCompleteHandlerFunctio-6W1npaBp6kAm

at close (/var/task/index.js:134:16)
at Runtime.handler (/var/task/index.js:74:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5) (RequestId: 204d7b86-c227-4256-aa6d-e07ccbb1df8a)


 ✅  org-stack

✨  Deployment time: 618.5s
