### ISSUE TITLE
Can I create a new OU and deploying a cloudFormation directly?(Question) 

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [pepperize/cdk-organizations#769]
Quick question:
Can I create a new OU and deploying a cloudFormation directly into it.
or I have to run the cdk for the Organisation creation first and then run a separate script with the cloudformation stack destined to that Organisation?

**Comment by gabrielsantosblanchet** [comment]
an other side of this question is:
does the organization unit create commes with a cdk bootstrap already deployed or it has to be donne manually?

**Comment by pflorek** [comment]
@gabrielsantosblanchet 

Nope, AWS Organizations is just about managing accounts. Additional one can enable AWS services or configure account limits by SCPs.

To provision resources in the account, one needs either to assume the default `OrganizationAccountAccessRole` in that account or use stack sets. Another approach would be something like ControlTower.

See this example to bootstrap your created accounts via CodePipeline: https://github.com/aws-samples/aws-bootstrap-kit-examples/blob/main/source/1-SDLC-organization/lib/cicd-stack.ts

Another option would be to enable stack sets in the organization: https://docs.aws.amazon.com/organizations/latest/userguide/services-that-can-integrate-cloudformation.html

**Comment by gabrielsantosblanchet** [comment]
Thanks for the clarification.
