### ISSUE TITLE
Adding metadata for cdk-nag and/or checkov

### ISSUE THREAD

**Issue by hans-d** [pepperize/cdk-organizations#902]
Seems that I cannot add metadata to the AWS::Lambda::Function generated from this library. Could this because the custom resource is hidden behind the private var? (https://github.com/pepperize/cdk-organizations/blob/main/src/organization.ts#L148)?

eg for
https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

Note I'm using the python lib for this.

**Comment by pflorek** [comment]
Hey @hans-d ,

cdk-nag is powered by CDK `Aspect`. It will be applied as visitor pattern to the construct tree. So applying cdk-nag to the stack or app should work.

This custom resources are placed into a nested stack with the singleton resource pattern.

On which level did you apply cdk-nag? Maybe drop here an additional example to elaborate: https://github.com/pepperize/cdk-organizations-example

**Comment by hans-d** [comment]
For cdk-nag, the only way to make it work was
```
        stack = cdk.Stack.of(self)
        stack_id = stack.stack_name
        NagSuppressions.add_resource_suppressions_by_path(
            stack=stack,
            path=[
                f'/{stack_id}/cdk-organizations.OrganizationProvider',
                f'/{stack_id}/cdk-organizations.AccountProvider',
                f'/{stack_id}/cdk-organizations.OrganizationalUnitProvider',
                f'/{stack_id}/cdk-organizations.TagResourceProvider',
                f'/{stack_id}/{id}/Organization/Root/RootCustomResource',
                f'/{stack_id}/AWS679f53fac002430cb0da5b7982bd2287',
            ],
            suppressions=[
                # The non-container Lambda function is not configured to use the latest runtime version
                {'id': 'AwsSolutions-L1', 'reason': 'external lib'},
                # The IAM user, role, or group uses AWS managed policies
                {'id': 'AwsSolutions-IAM4', 'reason': 'external lib'},
                # The IAM entity contains wildcard permissions
                {'id': 'AwsSolutions-IAM5', 'reason': 'external lib'},
            ],
            apply_to_children=True,
        )
```
Eg, attaching just to the stack or resource would not provide the suppressions.

For checkov, I was not able to find a workaround yet.

**Comment by pflorek** [comment]
Hey @hans-d ,

we've added cdk-nag: https://github.com/pepperize/cdk-organizations/blob/main/test/cdk-nag.test.ts

I guess the findings are either acceptable or exists by design, i.e. the custom resources needs to create and update any '*' org resource. If you need them more precise, it would be great if you open a PR with more strict policies. Also if there is a need to avoid the managed lambda execution policy

I'm not sure regarding checkov and open for any PR.

**Comment by hans-d** [comment]
Expecting these kind of exceptions indeed.

For checkov, so far it looks like I need access to the L1 construct to add the exceptions (haven't been successful yet by applying them on a different level).

**Comment by pflorek** [comment]
Hey @hans-d ,

maybe you can open a PR here, on that we can collaborate on together.
